# Generated by Django 6.0.5 on 2026-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_unlockedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone name, auto-detected from the browser. Drives streaks, daily resets, and deadlines in the user's local time.", max_length=64),
        ),
    ]
