# Generated by Django 6.0.5 on 2026-07-29 23:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('current_skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('daily_minutes', models.PositiveIntegerField(default=60)),
                ('target_deadline', models.DateField(blank=True, null=True)),
                ('learning_preference', models.CharField(choices=[('video', 'Video-based'), ('reading', 'Reading / Docs'), ('hands_on', 'Hands-on / Project-based'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('existing_skills', models.TextField(blank=True, help_text='Comma-separated skills the user already has')),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('budget', models.CharField(choices=[('free', 'Free only'), ('paid', 'Paid OK'), ('mixed', 'Free preferred, paid if needed')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_phase_index', models.PositiveIntegerField(default=0)),
                ('overall_completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('xp_total_available', models.PositiveIntegerField(default=0)),
                ('day_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('predicted_completion_date', models.DateField(blank=True, null=True)),
                ('success_probability', models.PositiveSmallIntegerField(default=0)),
                ('learning_speed', models.CharField(choices=[('slow', 'Slower than plan'), ('steady', 'On pace'), ('fast', 'Ahead of plan')], default='steady', max_length=10)),
                ('consistency_score', models.PositiveSmallIntegerField(default=0)),
                ('what_to_learn_next', models.JSONField(blank=True, default=list)),
                ('what_to_skip', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('learning_hacks', models.JSONField(blank=True, default=list)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('generation_failed', models.BooleanField(default=False)),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='roadmap.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('completion_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed')], default='locked', max_length=10)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_finish_date', models.DateField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('roadmap', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='roadmap.roadmapphase')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('youtube', 'YouTube Channel/Video'), ('documentation', 'Documentation'), ('book', 'Book'), ('course', 'Course'), ('article', 'Article'), ('practice', 'Practice Website')], default='article', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='roadmap.roadmapphase')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['phase__order', 'resource_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('was_adaptive', models.BooleanField(default=False)),
                ('adaptive_note', models.CharField(blank=True, max_length=200)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to='roadmap.roadmap')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_missions', to='roadmap.roadmapphase')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('roadmap', 'date')},
            },
        ),
    ]
