# Generated by Django 6.0.5 on 2026-07-31 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapphase',
            name='next_mission_cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailymission',
            unique_together={('roadmap', 'phase', 'date')},
        ),
        migrations.CreateModel(
            name='RoadmapDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('current_skill_level', models.CharField(default='beginner', max_length=20)),
                ('daily_minutes', models.PositiveIntegerField(default=60)),
                ('target_deadline', models.DateField(blank=True, null=True)),
                ('learning_preference', models.CharField(default='mixed', max_length=20)),
                ('existing_skills', models.TextField(blank=True)),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('budget', models.CharField(default='free', max_length=10)),
                ('clarifying_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
