# Generated by Django 6.0.5 on 2026-07-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmapphase_next_mission_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapphase',
            name='next_mission_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
