# Generated by Django 6.0.5 on 2026-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmapphase_next_mission_attempted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapphase',
            name='next_mission_generating',
            field=models.BooleanField(default=False),
        ),
    ]
