# Generated by Django 6.0.5 on 2026-07-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_roadmapphase_next_mission_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapphase',
            name='is_remedial_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedial_phases', to='roadmap.roadmapphase'),
        ),
        migrations.CreateModel(
            name='PhaseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('total_marks', models.PositiveIntegerField(default=50)),
                ('passing_marks', models.PositiveIntegerField(default=16)),
                ('questions', models.JSONField(default=list)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='roadmap.roadmapphase')),
            ],
            options={
                'ordering': ['-attempt_number'],
            },
        ),
    ]
