# Generated by Django 6.0.5 on 2026-08-01 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('entry_text', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('ai_suggestions', models.JSONField(blank=True, default=list)),
                ('ai_mood_tag', models.CharField(blank=True, max_length=40)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='one_journal_entry_per_user_per_day')],
            },
        ),
    ]
