# Generated by Django 6.0.5 on 2026-08-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='one_journal_entry_per_user_per_day',
        ),
    ]
