# Generated by Django 6.0.5 on 2026-07-31 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', '3-Month Pass'), ('yearly', 'Yearly')], max_length=20)),
                ('is_lifetime', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal')], max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
