# Generated by Django 6.0.5 on 2026-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
