# Generated by Django 6.0.5 on 2026-08-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_amount_usersubscription_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='amount_usd',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], default='USD', max_length=3),
        ),
    ]
