# Generated by Django 6.0.5 on 2026-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzerreport',
            old_name='consistency_score',
            new_name='discipline_score',
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='evolution_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='focus_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='productivity_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='root_causes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='summary_text',
            field=models.TextField(blank=True),
        ),
    ]
