# Generated by Django 6.0.5 on 2026-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_consistency_score_analyzerreport_discipline_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='best_opportunity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='burnout_risk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='confidence_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='consistency_risk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='evolution_grade',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='expected_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='expected_level_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='expected_weekly_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='expected_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='failure_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='goal_failure_risk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='goal_probability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='hidden_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='opportunities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='productivity_decline_risk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='streak_break_risk',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='success_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='trend_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='verdict',
            field=models.TextField(blank=True),
        ),
    ]
