# Generated by Django 6.0.5 on 2026-08-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analyzerreport_best_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='boss_fight_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='diet_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='roadmap_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='todo_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='willpower_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
