# Generated by Django 6.0.5 on 2026-08-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analyzerreport_boss_fight_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='journal_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
