# Generated by Django 6.0.5 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_analyzerreport_journal_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='activity_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
